movies = [
    {"Name": "Inception", "Actress": "Elliot Page", "Actor": "Leonardo DiCaprio", "Year of Release": 2010, "Director": "Christopher Nolan", "Language": "English", "Movie Categories": "Sci-Fi", "Rating": 8.8},
    {"Name": "Titanic", "Actress": "Kate Winslet", "Actor": "Leonardo DiCaprio", "Year of Release": 1997, "Director": "James Cameron", "Language": "English", "Movie Categories": "Romance", "Rating": 7.9},
    {"Name": "Avatar", "Actress": "Zoe Saldana", "Actor": "Sam Worthington", "Year of Release": 2009, "Director": "James Cameron", "Language": "English", "Movie Categories": "Sci-Fi", "Rating": 7.8},
    {"Name": "Baahubali: The Beginning", "Actress": "Anushka Shetty", "Actor": "Prabhas", "Year of Release": 2015, "Director": "S. S. Rajamouli", "Language": "Telugu", "Movie Categories": "Action", "Rating": 8.0},
    {"Name": "Drishyam", "Actress": "Meena", "Actor": "Mohanlal", "Year of Release": 2013, "Director": "Jeethu Joseph", "Language": "Malayalam", "Movie Categories": "Thriller", "Rating": 8.3},
    {"Name": "3 Idiots", "Actress": "Kareena Kapoor", "Actor": "Aamir Khan", "Year of Release": 2009, "Director": "Rajkumar Hirani", "Language": "Hindi", "Movie Categories": "Comedy", "Rating": 8.4},
    {"Name": "The Dark Knight", "Actress": "Maggie Gyllenhaal", "Actor": "Christian Bale", "Year of Release": 2008, "Director": "Christopher Nolan", "Language": "English", "Movie Categories": "Action", "Rating": 9.0},
    {"Name": "PK", "Actress": "Anushka Sharma", "Actor": "Aamir Khan", "Year of Release": 2014, "Director": "Rajkumar Hirani", "Language": "Hindi", "Movie Categories": "Comedy", "Rating": 8.1},
    {"Name": "Interstellar", "Actress": "Anne Hathaway", "Actor": "Matthew McConaughey", "Year of Release": 2014, "Director": "Christopher Nolan", "Language": "English", "Movie Categories": "Sci-Fi", "Rating": 8.6},
    {"Name": "Frozen", "Actress": "Idina Menzel", "Actor": "Kristen Bell", "Year of Release": 2013, "Director": "Chris Buck", "Language": "English", "Movie Categories": "Animation", "Rating": 7.4},
    {"Name": "Premam", "Actress": "Sai Pallavi", "Actor": "Nivin Pauly", "Year of Release": 2015, "Director": "Alphonse Puthren", "Language": "Malayalam", "Movie Categories": "Romance", "Rating": 8.3},
    {"Name": "Bangalore Days", "Actress": "Nazriya Nazim", "Actor": "Dulquer Salmaan", "Year of Release": 2014, "Director": "Anjali Menon", "Language": "Malayalam", "Movie Categories": "Drama", "Rating": 8.3},
    {"Name": "Lucifer", "Actress": "Manju Warrier", "Actor": "Mohanlal", "Year of Release": 2019, "Director": "Prithviraj Sukumaran", "Language": "Malayalam", "Movie Categories": "Action", "Rating": 7.5},
    {"Name": "Jailer", "Actress": "Tamannaah", "Actor": "Rajinikanth", "Year of Release": 2023, "Director": "Nelson Dilipkumar", "Language": "Tamil", "Movie Categories": "Action", "Rating": 7.1},
    {"Name": "Vikram", "Actress": "Gayathrie", "Actor": "Kamal Haasan", "Year of Release": 2022, "Director": "Lokesh Kanagaraj", "Language": "Tamil", "Movie Categories": "Action", "Rating": 8.3},
    {"Name": "Master", "Actress": "Malavika Mohanan", "Actor": "Vijay", "Year of Release": 2021, "Director": "Lokesh Kanagaraj", "Language": "Tamil", "Movie Categories": "Action", "Rating": 7.3},
    {"Name": "RRR", "Actress": "Alia Bhatt", "Actor": "Ram Charan", "Year of Release": 2022, "Director": "S. S. Rajamouli", "Language": "Telugu", "Movie Categories": "Action", "Rating": 7.8},
    {"Name": "Dangal", "Actress": "Fatima Sana Shaikh", "Actor": "Aamir Khan", "Year of Release": 2016, "Director": "Nitesh Tiwari", "Language": "Hindi", "Movie Categories": "Sports", "Rating": 8.3},
    {"Name": "Queen", "Actress": "Kangana Ranaut", "Actor": "Rajkummar Rao", "Year of Release": 2013, "Director": "Vikas Bahl", "Language": "Hindi", "Movie Categories": "Comedy", "Rating": 8.2},
    {"Name": "Andhadhun", "Actress": "Tabu", "Actor": "Ayushmann Khurrana", "Year of Release": 2018, "Director": "Sriram Raghavan", "Language": "Hindi", "Movie Categories": "Thriller", "Rating": 8.2},
    {"Name": "The Shawshank Redemption", "Actress": "Renee Blaine", "Actor": "Tim Robbins", "Year of Release": 1994, "Director": "Frank Darabont", "Language": "English", "Movie Categories": "Drama", "Rating": 9.3},
    {"Name": "The Godfather", "Actress": "Diane Keaton", "Actor": "Al Pacino", "Year of Release": 1972, "Director": "Francis Ford Coppola", "Language": "English", "Movie Categories": "Crime", "Rating": 9.2},
    {"Name": "Forrest Gump", "Actress": "Robin Wright", "Actor": "Tom Hanks", "Year of Release": 1994, "Director": "Robert Zemeckis", "Language": "English", "Movie Categories": "Drama", "Rating": 8.8},
    {"Name": "The Matrix", "Actress": "Carrie-Anne Moss", "Actor": "Keanu Reeves", "Year of Release": 1999, "Director": "The Wachowskis", "Language": "English", "Movie Categories": "Sci-Fi", "Rating": 8.7},
    {"Name": "Gladiator", "Actress": "Connie Nielsen", "Actor": "Russell Crowe", "Year of Release": 2000, "Director": "Ridley Scott", "Language": "English", "Movie Categories": "Action", "Rating": 8.5},
    {"Name": "Parasite", "Actress": "Cho Yeo-jeong", "Actor": "Song Kang-ho", "Year of Release": 2019, "Director": "Bong Joon-ho", "Language": "Korean", "Movie Categories": "Thriller", "Rating": 8.5},
    {"Name": "KGF Chapter 1", "Actress": "Srinidhi Shetty", "Actor": "Yash", "Year of Release": 2018, "Director": "Prashanth Neel", "Language": "Kannada", "Movie Categories": "Action", "Rating": 8.2},
    {"Name": "KGF Chapter 2", "Actress": "Srinidhi Shetty", "Actor": "Yash", "Year of Release": 2022, "Director": "Prashanth Neel", "Language": "Kannada", "Movie Categories": "Action", "Rating": 8.3},
    {"Name": "Minnal Murali", "Actress": "Shelly Kishore", "Actor": "Tovino Thomas", "Year of Release": 2021, "Director": "Basil Joseph", "Language": "Malayalam", "Movie Categories": "Superhero", "Rating": 7.8},
    {"Name": "Hridayam", "Actress": "Darshana Rajendran", "Actor": "Pranav Mohanlal", "Year of Release": 2022, "Director": "Vineeth Sreenivasan", "Language": "Malayalam", "Movie Categories": "Romance", "Rating": 8.1},
    {"Name": "Varisu", "Actress": "Rashmika Mandanna", "Actor": "Vijay", "Year of Release": 2023, "Director": "Vamshi Paidipally", "Language": "Tamil", "Movie Categories": "Drama", "Rating": 6.0},
    {"Name": "Pathaan", "Actress": "Deepika Padukone", "Actor": "Shah Rukh Khan", "Year of Release": 2023, "Director": "Siddharth Anand", "Language": "Hindi", "Movie Categories": "Action", "Rating": 6.6},
    {"Name": "Jawan", "Actress": "Nayanthara", "Actor": "Shah Rukh Khan", "Year of Release": 2023, "Director": "Atlee", "Language": "Hindi", "Movie Categories": "Action", "Rating": 7.0},
    {"Name": "Gadar 2", "Actress": "Ameesha Patel", "Actor": "Sunny Deol", "Year of Release": 2023, "Director": "Anil Sharma", "Language": "Hindi", "Movie Categories": "Action", "Rating": 5.5},
    {"Name": "Oppenheimer", "Actress": "Emily Blunt", "Actor": "Cillian Murphy", "Year of Release": 2023, "Director": "Christopher Nolan", "Language": "English", "Movie Categories": "Biography", "Rating": 8.4},
    {"Name": "Barbie", "Actress": "Margot Robbie", "Actor": "Ryan Gosling", "Year of Release": 2023, "Director": "Greta Gerwig", "Language": "English", "Movie Categories": "Fantasy", "Rating": 7.0},
    {"Name": "96", "Actress": "Trisha", "Actor": "Vijay Sethupathi", "Year of Release": 2018, "Director": "C. Prem Kumar", "Language": "Tamil", "Movie Categories": "Romance", "Rating": 8.5},
    {"Name": "Kaithi", "Actress": "Karthika Nair", "Actor": "Karthi", "Year of Release": 2019, "Director": "Lokesh Kanagaraj", "Language": "Tamil", "Movie Categories": "Action", "Rating": 8.5},
    {"Name": "Thani Oruvan", "Actress": "Nayanthara", "Actor": "Jayam Ravi", "Year of Release": 2015, "Director": "Mohan Raja", "Language": "Tamil", "Movie Categories": "Thriller", "Rating": 8.4},
    {"Name": "Uyare", "Actress": "Parvathy Thiruvothu", "Actor": "Asif Ali", "Year of Release": 2019, "Director": "Manu Ashokan", "Language": "Malayalam", "Movie Categories": "Drama", "Rating": 8.1},
    {"Name": "Take Off", "Actress": "Parvathy Thiruvothu", "Actor": "Kunchacko Boban", "Year of Release": 2017, "Director": "Mahesh Narayanan", "Language": "Malayalam", "Movie Categories": "Thriller", "Rating": 8.2},
    {"Name": "Charlie", "Actress": "Parvathy Thiruvothu", "Actor": "Dulquer Salmaan", "Year of Release": 2015, "Director": "Martin Prakkat", "Language": "Malayalam", "Movie Categories": "Drama", "Rating": 8.0},
    {"Name": "Ala Vaikunthapurramuloo", "Actress": "Pooja Hegde", "Actor": "Allu Arjun", "Year of Release": 2020, "Director": "Trivikram Srinivas", "Language": "Telugu", "Movie Categories": "Drama", "Rating": 7.3},
    {"Name": "Arjun Reddy", "Actress": "Shalini Pandey", "Actor": "Vijay Deverakonda", "Year of Release": 2017, "Director": "Sandeep Reddy Vanga", "Language": "Telugu", "Movie Categories": "Romance", "Rating": 8.1},
    {"Name": "Sita Ramam", "Actress": "Mrunal Thakur", "Actor": "Dulquer Salmaan", "Year of Release": 2022, "Director": "Hanu Raghavapudi", "Language": "Telugu", "Movie Categories": "Romance", "Rating": 8.6},
    {"Name": "Dilwale Dulhania Le Jayenge", "Actress": "Kajol", "Actor": "Shah Rukh Khan", "Year of Release": 1995, "Director": "Aditya Chopra", "Language": "Hindi", "Movie Categories": "Romance", "Rating": 8.0},
    {"Name": "My Name Is Khan", "Actress": "Kajol", "Actor": "Shah Rukh Khan", "Year of Release": 2010, "Director": "Karan Johar", "Language": "Hindi", "Movie Categories": "Drama", "Rating": 8.0},
    {"Name": "The Lion King", "Actress": "Nala (voice)", "Actor": "Matthew Broderick", "Year of Release": 1994, "Director": "Roger Allers", "Language": "English", "Movie Categories": "Animation", "Rating": 8.5},
    {"Name": "Avengers: Endgame", "Actress": "Scarlett Johansson", "Actor": "Robert Downey Jr.", "Year of Release": 2019, "Director": "Anthony Russo", "Language": "English", "Movie Categories": "Superhero", "Rating": 8.4}
]
rating_gt=[di.get("Name")for di in movies if di.get("Rating")>8.0]
print(rating_gt)